export const PERMISSIONS=["dashboard.read","children.read","children.create","children.update","children.archive","children.medical.read","parents.read","parents.create","parents.update","parents.link","parents.invite","classes.read","classes.create","classes.update","classes.archive","classes.assign_teacher","attendance.read","attendance.record","attendance.correct","attendance.approve","attendance.pickup_manage","activities.read","activities.create","activities.update","activities.archive","activities.media_manage","homework.read","homework.create","homework.update","homework.review_submission","absences.read","absences.submit","absences.review","complaints.read","complaints.create","complaints.respond","complaints.internal_note","complaints.assign","payments.read","payments.create","payments.update","payments.issue_receipt","payments.export","staff.read","staff.invite","staff.update","announcements.read","announcements.publish","reports.operational","reports.financial","settings.manage","platform.manage","parent.portal"] as const;
export type Permission=typeof PERMISSIONS[number];
const admin=PERMISSIONS.filter(p=>p!=="platform.manage"&&p!=="parent.portal");
const grants:Record<string,readonly Permission[]>={
SUPER_ADMIN:["platform.manage"],
ADMIN:admin,
MANAGER:["dashboard.read","children.read","children.create","children.update","children.archive","children.medical.read","parents.read","parents.create","parents.update","parents.link","parents.invite","classes.read","classes.create","classes.update","classes.archive","classes.assign_teacher","attendance.read","attendance.record","attendance.correct","attendance.approve","attendance.pickup_manage","activities.read","activities.create","activities.update","activities.archive","activities.media_manage","homework.read","homework.create","homework.update","homework.review_submission","absences.read","absences.review","complaints.read","complaints.respond","complaints.internal_note","complaints.assign","announcements.read","announcements.publish","reports.operational","staff.read"],
TEACHER:["dashboard.read","children.read","classes.read","attendance.read","attendance.record","attendance.correct","activities.read","activities.create","activities.update","activities.media_manage","homework.read","homework.create","homework.update","homework.review_submission","absences.read","announcements.read"],
ACCOUNTANT:["dashboard.read","children.read","parents.read","payments.read","payments.create","payments.update","payments.issue_receipt","payments.export","reports.financial"],
PARENT:["parent.portal","children.read","attendance.read","activities.read","homework.read","absences.read","absences.submit","complaints.read","complaints.create","payments.read","announcements.read"]};
export const STAFF_ROLES=["ADMIN","MANAGER","TEACHER","ACCOUNTANT"];
export function hasPermission(role:string,permission:Permission){return grants[role]?.includes(permission)??false}
export function permissionsForRole(role:string){return [...(grants[role]??[])]}
