import{prisma}from"./prisma";import{ForbiddenError}from"./auth";import type{AuthContext}from"./auth-context";import{requireFeature}from"./subscriptions/service";
function denied():never{throw new ForbiddenError("Resource unavailable")}
export async function assertClassAccess(ctx:AuthContext,classId:string){const row=await prisma.classRoom.findFirst({where:{id:classId,organizationId:ctx.organizationId},select:{id:true}});if(!row||(ctx.role==="TEACHER"&&!ctx.authorizedClassIds?.includes(classId)))denied();return row}
export async function assertChildAccess(ctx:AuthContext,childId:string){const row=await prisma.child.findFirst({where:{id:childId,organizationId:ctx.organizationId,...(ctx.role==="PARENT"?{parents:{some:{parentId:ctx.parentId??"__none__"}}}:ctx.role==="TEACHER"?{classId:{in:ctx.authorizedClassIds??[]}}:{})},select:{id:true,classId:true}});if(!row)denied();return row}
export async function assertParentChild(ctx:AuthContext,parentId:string,childId:string){const row=await prisma.parentChild.findFirst({where:{organizationId:ctx.organizationId,parentId,childId}});if(!row)denied();return row}
export async function assertComplaintAccess(ctx:AuthContext,id:string){await requireFeature(ctx,"advancedCommunication");const row=await prisma.complaint.findFirst({where:{id,organizationId:ctx.organizationId,...(ctx.role==="PARENT"?{parentId:ctx.parentId??"__none__"}:{})}});if(!row)denied();return row}
export async function assertPaymentAccess(ctx:AuthContext,id:string){const row=await prisma.payment.findFirst({where:{id,organizationId:ctx.organizationId,...(ctx.role==="PARENT"?{parentId:ctx.parentId??"__none__"}:{})}});if(!row)denied();return row}
export async function assertHomeworkAccess(ctx:AuthContext,id:string){await requireFeature(ctx,"homework");const row=await prisma.homework.findFirst({where:{id,organizationId:ctx.organizationId,...(ctx.role==="TEACHER"?{classId:{in:ctx.authorizedClassIds??[]}}:ctx.role==="PARENT"?{status:"PUBLISHED",active:true,OR:[{assignments:{some:{child:{parents:{some:{parentId:ctx.parentId??"__none__"}}},required:true}}},{AND:[{assignments:{none:{}}},{class:{children:{some:{active:true,parents:{some:{parentId:ctx.parentId??"__none__"}}}}}}]}]}:{})}});if(!row)denied();return row}
export async function assertActivityAccess(ctx:AuthContext,id:string){const row=await prisma.activity.findFirst({where:{id,organizationId:ctx.organizationId,...(ctx.role==="TEACHER"?{OR:[{classId:{in:ctx.authorizedClassIds??[]}},{createdById:ctx.id}]}:ctx.role==="PARENT"?{OR:[{child:{parents:{some:{parentId:ctx.parentId??"__none__"}}}},{class:{children:{some:{parents:{some:{parentId:ctx.parentId??"__none__"}}}}}}]}:{})}});if(!row)denied();return row}
